# Generated by Django 3.2.13 on 2022-06-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_auto_20220621_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linktocrawl',
            name='crawled_links',
        ),
        migrations.AddField(
            model_name='crawledlink',
            name='link_to_crawl',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spider.linktocrawl'),
        ),
    ]
